### ISSUE TITLE
There is now a withe line at the top bar of Youtube

### ISSUE THREAD

**Issue by LautaroL20** [omnidevZero/YouTubeRedux#91] opened 2022-11-09 19:45 UTC
There is now a withe line at the top bar of Youtube which would be nice if it can be restored back to their previous color which was dark gray?

![Withe line](https://user-images.githubusercontent.com/12244376/200926145-e4a416de-2c2b-419c-8366-3b848885c63c.png)

**Comment by omnidevZero** [comment] 2022-11-15 18:59
This was actually caused by a YouTube issue due to which the top bar was missing a [dark] attribute under certain circumstances which caused Redux to apply styles from the light theme there. Anyway, fixed!

**Comment by omnidevZero** [comment] 2022-11-25 20:00
Closing as it was fixed a while ago. If the issue still occurs feel free to reopen the issue.

**Closed by omnidevZero** 2022-11-25 20:00 UTC
