### ISSUE TITLE
Disable Miniplayer selection only partially works.

### ISSUE THREAD

**Issue by Amariithynar** [omnidevZero/YouTubeRedux#109] opened 2022-11-25 11:49 UTC
It hides the window, but the video is still playing. You keep getting the audio after clicking off of a video (why was this ever a thing, Youtube?! It's so goddamn stupid!).

**Comment by omnidevZero** [comment] 2022-11-25 19:58
I couldn't reproduce it. Which browser are you using?

**Comment by Amariithynar** [comment] 2022-11-26 15:53
Firefox. Version 107.0, aka up-to-date. It doesn't happen all the time, and the miniplayer button is disabled while it's also disabled, but if you go to say, subscriptions while watching a video, it sometimes puts the video into miniplayer. With it active, it disables the video frame that would appear, but the video itself keeps playing, and you get the audio from it, until you click onto another video or refresh the page.

**Comment by LautaroL20** [comment] 2022-11-27 15:25
This issue happens to me too, I could record a video showing the issue if needed.

**Comment by omnidevZero** [comment] 2022-11-27 18:06
> but if you go to say, subscriptions while watching a video

Oh right, that's the case! Going from video page to subscriptions I was able to easily reproduce it. The issue was that I was testing it by going back to the homepage and that's also how the extension works - it checks if the user is on the homepage and then closes the miniplayer. Anyway, I removed the condition that checked for the specific page, will be fixed in the next update, thanks!

**Closed** 2024-12-24 20:02 UTC
