### ISSUE TITLE
Crashing when enabling "Show precise values for likes/dislikes"

### ISSUE THREAD

**Issue by V1lh0** [omnidevZero/YouTubeRedux#259] opened 2024-10-19 12:00 UTC
Whenever the "Show precise values for likes/dislikes" option is enabled, the whole site crashes and won't load anything. Disabling this option returns it back to normal.

**Comment by omnidevZero** [comment] 2024-10-19 12:41
Closing this one as duplicate of #257. Anyway it should be fixed in Firefox as of now and in Chrome once it's approved.

**Closed by omnidevZero** 2024-10-19 12:41 UTC
