### ISSUE TITLE
Search bar text now aligned to the left, bugged when in focus on Firefox

### ISSUE THREAD

**Issue by sccabe** [omnidevZero/YouTubeRedux#47] opened 2022-08-03 19:44 UTC
![image](https://user-images.githubusercontent.com/83051661/182695281-2d059bec-92b7-41c7-bd94-66ad85d2d9a9.png)
Chromium browsers don't suffer from this issue, text is also properly aligned to left side but there's no more magnifying glass icon inside the bar

**Comment by TorutheRedFox** [comment] 2022-08-04 10:06
the icon is supposed to be gone (as there wasn't one prior)

there's something up with the selector for the styles used to hide it

**Comment by TorutheRedFox** [comment] 2022-08-04 10:07
so apart from the search icon appearing when it shouldn't, this is intentional

**Comment by TorutheRedFox** [comment] 2022-08-04 10:07
this is how it's _supposed_ to look
![image](https://user-images.githubusercontent.com/15708278/182821732-8980bbe0-5f95-4445-b186-20c7c13715a7.png)

**Comment by omnidevZero** [comment] 2022-08-04 17:14
I checked in Firefox 103.0.1 and it works properly for me. I'll keep my eyes out for this one though. Let me know if there are any other prerequisites needed to reproduce this issue.

**Comment by sccabe** [comment] 2022-08-04 21:33
> I checked in Firefox 103.0.1 and it works properly for me. I'll keep my eyes out for this one though. Let me know if there are any other prerequisites needed to reproduce this issue.

I don't think so, I'm also on 103.0.1 and none of my other extensions are causing this

**Comment by omnidevZero** [comment] 2022-08-04 21:50
Weird stuff. This is the CSS responsible for hiding it:

`ytd-searchbox[has-focus] #search-icon.ytd-searchbox {
			display: none;
		}`

No matter what I did it's always hitting that magnifying glass icon and hides it properly. Could you check if the issue still occurs in in private browsing window?

**Comment by sccabe** [comment] 2022-08-08 11:05
I finally figured out what's causing the problem: Violentmonkey. I do use a userscript to restore the old icons on top of Redux but the extension itself is the cause because issue persisted after I disabled only the script. After the Aug 6 update it also messes up the search bar's height and the video page layout:
![image](https://user-images.githubusercontent.com/83051661/183403982-ea8171ff-dfbb-44d4-80c5-f0eb44fe812f.png)

**Comment by Thespikedballofdoom** [comment] 2022-08-09 08:43
Violentmonkey continues to dissapoint. Why does the open source script manager have to be consistently shittier?
I'm glad I went through here instead of opening an issue for this, I came because of it.

**Comment by omnidevZero** [comment] 2022-08-09 11:49
I did some testing around it and it appears that the order of loading extensions is important. You CAN use both Violentmonkey and YouTube Redux without issues but only if you **install Violentmonkey first** and then install YouTube Redux (remember to do a backup of your userscripts when doing so). Reversed order causes the aforementioned issue. 

No idea why that issue specifically affects Violentmonkey as I also tried Tampermonkey and Firemonkey and both work correctly. Having Violentmonkey installed after Redux causes it to apply the styles on YT after Redux, overriding them, and the fact that they are allowed to be overriden now comes from [this commit](https://github.com/omnidevZero/YouTubeRedux/commit/6389008b7b2415540b97d6043169361354d18c58) which actually aimed to allow these overrides "just in case".

**Comment by omnidevZero** [comment] 2022-09-06 16:58
Dropping by to let you know it will be fixed shortly.

**Closed** 2022-11-25 20:31 UTC
Labels: couldn't reproduce
