### ISSUE TITLE
Description layout broken

### ISSUE THREAD

**Issue by lynrayy** [omnidevZero/YouTubeRedux#74] opened 2022-10-14 01:21 UTC
![image](https://user-images.githubusercontent.com/59417884/195740455-61d59170-f59d-497b-9a6a-a7eedf88b39a.png)

**Comment by KingGamingYT** [comment] 2022-10-14 10:55
The description area seems fine. What you're describing is YouTube's new layout changes which have been affecting people in different ways. In your case, it messes up the button placements. Unfortunately we'll just have to wait for a patch.

**Comment by lynrayy** [comment] 2022-10-14 14:51
_Unfortunately we'll just have to wait for a patch._
Yeah i know. Just want to know if plugin (addon) still in development

**Comment by gameshowrecaps** [comment] 2022-10-15 17:13
Apparently it's the experimental layout. I've gotten the older layout.

**Comment by KingGamingYT** [comment] 2022-10-15 17:17
> Apparently it's the experimental layout. I've gotten the older layout.

Yes, it is experimental, but from what I can tell more users have it compare to users who don’t

**Comment by gameshowrecaps** [comment] 2022-10-17 20:54
I've been put back into the experimental new layout after 4 days. I've been getting it back and forth. Hopefully devs do fix this soon.

**Comment by gameshowrecaps** [comment] 2022-10-18 20:00
UPDATE: My alt and personal account have the old layout, while my main has the newer broken layout. It is definitely on certain accounts, however, sometimes I go back and forth. Also minor, but YouTube changed the search layout a bit (it's no longer centered).

**Comment by Franck-Nein** [comment] 2022-10-18 20:15
The off centered search bar is caused by YouTube Redux, if you disable "Extra layout changes" it goes back to the center.
I think it has always done that, but my earliest screenshot of from August 2019.

**Comment by gameshowrecaps** [comment] 2022-10-24 20:28
Welp. It's official. YouTube is officially rolling out this layout, and this is getting out of A/B testing.

**Comment by KingGamingYT** [comment] 2022-10-25 04:05
Considering it was in a creators video on their youtube creators channel, it isn't very surprising

**Comment by gameshowrecaps** [comment] 2022-10-25 22:51
Unfortunately, I've been trying to find extensions/CSS codes that restore the old layout but it still breaks YouTube Redux. Hopefully someone finds a way to revert the layout.

**Comment by 1chan-level-journalist** [comment] 2022-10-27 00:46
I played around with CSS and managed to create a custom style that removes most of the circle BS around the buttons, thumbnails and other UI elements. Description area is still FUBAR'd though, unfortunately. Still, should be enough to wait out the storm until Redux updates.
This style is designed to work with Redux and was specifically made around Dark theme (you can use it with Light theme, but you'll have to remove the lines marked with comments)
In order to install it, create a custom CSS in Stylish/Stylem/what-have-you and copy-paste the contents of the attached file:
[restore.txt](https://github.com/omnidevZero/YouTubeRedux/files/9874739/restore.txt)

**Comment by KingGamingYT** [comment] 2022-10-27 02:47
> I played around with CSS and managed to create a custom style that removes most of the circle BS around the buttons, thumbnails and other UI elements. Description area is still FUBAR'd though, unfortunately. Still, should be enough to wait out the storm until Redux updates. This style is designed to work with Redux and was specifically made around Dark theme (you can use it with Light theme, but you'll have to remove the lines marked with comments) In order to install it, create a custom CSS in Stylish/Stylem/what-have-you and copy-paste the contents of the attached file: [restore.txt](https://github.com/omnidevZero/YouTubeRedux/files/9874739/restore.txt)

![image](https://user-images.githubusercontent.com/45918062/198178849-b6fa033e-e937-47e5-9f19-5d6f18d9cd51.png)
y'know, despite the fact everything is just badly cropped squares instead of circles now, I like it much more, now I just need to figure out how to get the buttons to format properly on the page again. Thanks!

**Comment by 1chan-level-journalist** [comment] 2022-10-27 22:03
> ![image](https://user-images.githubusercontent.com/45918062/198178849-b6fa033e-e937-47e5-9f19-5d6f18d9cd51.png) y'know, despite the fact everything is just badly cropped squares instead of circles now, I like it much more, now I just need to figure out how to get the buttons to format properly on the page again. Thanks!

Glad you liked it! I had spare time today so I tuned it up some more. I couldn't figure out how to move the three-dot button over to the left, but even now the description area looks almost kinda alright:
![feex](https://user-images.githubusercontent.com/16210758/198406620-8a8c4061-9d13-4c40-8d65-42d4d40c1fd9.png)
I also added numerous fixes for the things I forgot to change.
[restore.txt](https://github.com/omnidevZero/YouTubeRedux/files/9883379/restore.txt)

**Comment by KingGamingYT** [comment] 2022-10-28 00:18
> > ![image](https://user-images.githubusercontent.com/45918062/198178849-b6fa033e-e937-47e5-9f19-5d6f18d9cd51.png) y'know, despite the fact everything is just badly cropped squares instead of circles now, I like it much more, now I just need to figure out how to get the buttons to format properly on the page again. Thanks!
> 
> Glad you liked it! I had some spare time today so I tuned it up some more. I couldn't figure out how to move the three-dot button over to the left, but even now the description area looks almost kinda alright: ![feex](https://user-images.githubusercontent.com/16210758/198406620-8a8c4061-9d13-4c40-8d65-42d4d40c1fd9.png) I also added numerous fixes for the things I forgot to fix the first time around. [restore.txt](https://github.com/omnidevZero/YouTubeRedux/files/9883528/restore.txt)

This is a great temporary solution until #77 is approved and merged. Thanks for all your efforts.

**Comment by lynrayy** [comment] 2022-10-28 00:19
[KingGamingYT](https://github.com/KingGamingYT)

How to use it?

**Comment by KingGamingYT** [comment] 2022-10-28 00:22
> [KingGamingYT](https://github.com/KingGamingYT)
> 
> How to use it?

You'll need something like the chrome/firefox extension Stylus(https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en) that lets you write custom webpage css.

**Comment by lynrayy** [comment] 2022-10-28 00:23
I don't know how to import txt file in this CRAPPY extension. It wants .json file

**Comment by KingGamingYT** [comment] 2022-10-28 00:27
> I don't know how to import txt file in this CRAPPY extension. It wants .json file

![image](https://user-images.githubusercontent.com/45918062/198421651-c7b193e6-237e-4520-aedf-fdf99cb33878.png)
"Write new style"
![image](https://user-images.githubusercontent.com/45918062/198421691-64983852-5183-438a-b17e-ee72d7c15b14.png)
Paste the code from the text file
![image](https://user-images.githubusercontent.com/45918062/198421720-0b1d0504-9cb5-45c6-9f74-de89df0dc662.png)
Save

Simple as that.

**Comment by lynrayy** [comment] 2022-10-28 00:30
Very bad style. My layout now broken
![image](https://user-images.githubusercontent.com/59417884/198421936-664bd863-6bd6-485d-b51b-f4a48010d0a1.png)

**Comment by gameshowrecaps** [comment] 2022-10-28 00:30
Good fix, but the dislike button looks off (probably because Return YouTube Dislike compatibility is broken, the devs are working on it)

**Comment by KingGamingYT** [comment] 2022-10-28 00:37
> Very bad style. My layout now broken ![image](https://user-images.githubusercontent.com/59417884/198421936-664bd863-6bd6-485d-b51b-f4a48010d0a1.png)

As explicitly stated in their post, it was designed for dark mode. If you want light mode to work you'll have to modify some stuff, the likes of which I don't know.

**Comment by BlackCanboy9** [comment] 2022-10-28 07:20
Thank you. I Figured out how to change the color but how do get the text smaller? Ive been trying for a hour but cant figure it out.

**Comment by 1chan-level-journalist** [comment] 2022-10-28 10:02
> Very bad style. My layout now broken ![image](https://user-images.githubusercontent.com/59417884/198421936-664bd863-6bd6-485d-b51b-f4a48010d0a1.png)
All you have to do is remove the lines that have `/*remove if you want to use Light theme*/ ` in them. Something I mentioned before.
> Thank you. I Figured out how to change the color but how do get the text smaller? Ive been trying for a hour but cant figure it out.
The CSS property that lets you do that is `font-size`. Where exactly do you want the text to get smaller?

**Comment by BlackCanboy9** [comment] 2022-10-28 10:21
under the video where the "Save" and "Share" icons are. Mine are way to big for some reason

**Comment by 1chan-level-journalist** [comment] 2022-10-28 10:29
> under the video where the "Save" and "Share" icons are. Mine are way to big for some reason

```
.redux-moved-info > yt-button-shape > button > .yt-spec-button-shape-next--button-text-content > .yt-core-attributed-string--white-space-no-wrap {
  font-size: 11px;
  text-transform: none;
}
```

**Comment by KingGamingYT** [comment] 2022-10-28 10:43
I’ll also note how it seems like redux’s ability to hide buttons like clip has been borked on some videos, but with how fragile the layout is right now that’s to be expected.

**Comment by BlackCanboy9** [comment] 2022-10-28 11:25
It works. Thanks!. Hopefully redux will get updated soon but this is a good alternative until then.

**Comment by KingGamingYT** [comment] 2022-10-29 03:36
Another thing: This may be a problem with redux itself, but when you like or dislike a video the icons don't actually change.
@1chan-level-journalist

**Comment by 1chan-level-journalist** [comment] 2022-10-29 10:54
> Another thing: This may be a problem with redux itself, but when you like or dislike a video the icons don't actually change. @1chan-level-journalist

I figured out a fix for that as well, but what code you'll have to use depends on whether you want to use old icons for likes/dislikes or not.

If you're fine with new icons:
```
button[aria-pressed="true"] > .yt-spec-button-shape-next__icon > yt-icon > svg {fill: #3ea6ff !important;}
button[aria-pressed="true"] > div > span {color: #3ea6ff !important;}
```

If you want to use old icons:
```
#segmented-like-button > ytd-toggle-button-renderer > yt-button-shape > button[aria-pressed="false"] > div > yt-icon {
content: url('moz-extension://bfaec30f-6292-460c-8804-ba78bd0f0ffe/images/like.png') !important;
filter: contrast(0);
height: 17px !important;
width: 17px !important;
}
#segmented-like-button > ytd-toggle-button-renderer > yt-button-shape > button[aria-pressed="true"] > div > yt-icon {
content: url('moz-extension://bfaec30f-6292-460c-8804-ba78bd0f0ffe/images/like-pressed.png') !important;
filter: contrast(1);
height: 17px !important;
width: 17px !important;
}
button[aria-pressed="true"] > div > span {color: #3ea6ff !important;}
#segmented-dislike-button > ytd-toggle-button-renderer > yt-button-shape > button[aria-pressed="false"] > div > yt-icon {
content: url('moz-extension://bfaec30f-6292-460c-8804-ba78bd0f0ffe/images/dislike.png') !important;
filter: contrast(0);
height: 17px !important;
width: 17px !important;
}
#segmented-dislike-button > ytd-toggle-button-renderer > yt-button-shape > button[aria-pressed="true"] > div > yt-icon {
content: url('moz-extension://bfaec30f-6292-460c-8804-ba78bd0f0ffe/images/dislike-pressed.png') !important;
filter: contrast(1);
height: 17px !important;
width: 17px !important;
}
#like-button > yt-button-shape > button[aria-pressed="true"] > div > yt-icon {
  content: url('moz-extension://bfaec30f-6292-460c-8804-ba78bd0f0ffe/images/like-pressed.png') !important;
  filter: contrast(1);
}
#dislike-button > yt-button-shape > button[aria-pressed="true"] > div > yt-icon {
  content: url('moz-extension://bfaec30f-6292-460c-8804-ba78bd0f0ffe/images/dislike-pressed.png') !important;
  filter: contrast(1);
}
```

**Comment by TorutheRedFox** [comment] 2022-10-29 12:20
wouldn't you be able to just make the stuff under `/*remove if you want to use Light theme*/ ` just not apply using a more specific css selector?

**Comment by KingGamingYT** [comment] 2022-10-29 17:18
> > Another thing: This may be a problem with redux itself, but when you like or dislike a video the icons don't actually change. @1chan-level-journalist
> 
> I figured out a fix for that as well, but what code you'll have to use depends on whether you want to use old icons for likes/dislikes or not.
> 
> If you're fine with new icons:
> 
> ```
> button[aria-pressed="true"] > .yt-spec-button-shape-next__icon > yt-icon > svg {fill: #3ea6ff !important;}
> button[aria-pressed="true"] > div > span {color: #3ea6ff !important;}
> ```
> 
> If you want to use old icons:
> 
> ```
> #segmented-like-button > ytd-toggle-button-renderer > yt-button-shape > button[aria-pressed="false"] > div > yt-icon {
> content: url('moz-extension://bfaec30f-6292-460c-8804-ba78bd0f0ffe/images/like.png') !important;
> filter: contrast(0);
> height: 17px !important;
> width: 17px !important;
> }
> #segmented-like-button > ytd-toggle-button-renderer > yt-button-shape > button[aria-pressed="true"] > div > yt-icon {
> content: url('moz-extension://bfaec30f-6292-460c-8804-ba78bd0f0ffe/images/like-pressed.png') !important;
> filter: contrast(1);
> height: 17px !important;
> width: 17px !important;
> }
> button[aria-pressed="true"] > div > span {color: #3ea6ff !important;}
> #segmented-dislike-button > ytd-toggle-button-renderer > yt-button-shape > button[aria-pressed="false"] > div > yt-icon {
> content: url('moz-extension://bfaec30f-6292-460c-8804-ba78bd0f0ffe/images/dislike.png') !important;
> filter: contrast(0);
> height: 17px !important;
> width: 17px !important;
> }
> #segmented-dislike-button > ytd-toggle-button-renderer > yt-button-shape > button[aria-pressed="true"] > div > yt-icon {
> content: url('moz-extension://bfaec30f-6292-460c-8804-ba78bd0f0ffe/images/dislike-pressed.png') !important;
> filter: contrast(1);
> height: 17px !important;
> width: 17px !important;
> }
> #like-button > yt-button-shape > button[aria-pressed="true"] > div > yt-icon {
>   content: url('moz-extension://bfaec30f-6292-460c-8804-ba78bd0f0ffe/images/like-pressed.png') !important;
>   filter: contrast(1);
> }
> #dislike-button > yt-button-shape > button[aria-pressed="true"] > div > yt-icon {
>   content: url('moz-extension://bfaec30f-6292-460c-8804-ba78bd0f0ffe/images/dislike-pressed.png') !important;
>   filter: contrast(1);
> }
> ```

Had to do a quick'n dirty patch for chrome but it yeah it works great
Here's what should be the extension "link":
Replace
'moz-extension://bfaec30f-6292-460c-8804-ba78bd0f0ffe'
with
'chrome-extension://mdgdgieddpndgjlmeblhjgljejejkikf'

**Comment by KingGamingYT** [comment] 2022-10-29 17:24
![image](https://user-images.githubusercontent.com/45918062/198844992-e8c47473-6484-418b-84ec-ff8f58b3f496.png)
"Federal regulations require me to warn you that this current layout patch...is looking _pretty_ good"

**Comment by KingGamingYT** [comment] 2022-10-29 17:57
After doing a bit of messing around I've seemed to bullshit my way into revealing the old subscribe button, which is seemingly not broken at all. I'll update this comment if I find anything else out
![image](https://user-images.githubusercontent.com/45918062/198846219-2b17f39e-5c86-467e-9a16-368ebbe9652c.png)

**Comment by 1chan-level-journalist** [comment] 2022-10-29 18:05
Looks like community posts got "rounded" too. The following code reverts them back to how they used to be:
```
#title-container > h2 > yt-formatted-string {
    font-family: Roboto !important;
font-weight: 500 !important;
font-size: 1.4rem !important;
line-height: 2rem !important;
max-height: 2rem !important;
overflow: hidden !important;
display: block !important;
-webkit-line-clamp: 1 !important;
text-overflow: ellipsis !important;
}
ytd-engagement-panel-section-list-renderer{border-radius: 0px !important;}
ytd-backstage-post-dialog-renderer[is-creation-dialog][rounded-container] {
  border-radius: 0px !important;
}
ytd-backstage-post-thread-renderer[rounded-container] {
  border-radius: 0px !important;
}
```

**Closed** 2022-10-29 18:09 UTC
